name: "Feature Request"
description: Request for a new Feature
title: "[Feature] "
labels: ["feature work", "feature request", "needs triage"]
body:
    - type: textarea
      id: repro
      attributes:
          label: Feature Description
          description: "What feature you are looking for?"
          value: |
              ...
      validations:
          required: true
    - type: dropdown
      attributes:
          label: Types
          description: What type is the feature classified as?
          multiple: true
          options:
              - Matter Device Types
              - Matter Clusters
              - Matter Attribute
              - Others
      validations:
          required: true
    - type: input
      attributes:
          label: Github SDK version
          description: Specify the commit ID of the GitHub SDK or Matter version for the feature.
      validations:
          required: true
    - type: dropdown
      attributes:
          label: Integrated Circuit (IC)
          description: Which IC is the target for implementing the feature?
          multiple: true
          options:
            - AmebaDplus (RTL8721Dx)
            - AmebaLite (RTL8720E/RTL8726E)
            - AmebaSmart (RTL8730E)
            - other
    - type: textarea
      attributes:
          label: Other Inputs
          description: Other inputs (e.g., Links, References, Images), if applicable.
      validations:
          required: false
