# Matter Directories
#----------------------------------------#
set(CHIP_DIR           "${BASEDIR}/third_party/connectedhomeip")
set(MATTER_DIR         "${BASEDIR}/component/application/matter")
set(MATTER_CMAKE_DIR   "${MATTER_DIR}/project/cmake")
set(MATTER_API_DIR     "${MATTER_DIR}/api")
set(MATTER_CORE_DIR    "${MATTER_DIR}/core")
set(MATTER_DRIVER_DIR  "${MATTER_DIR}/drivers")
set(MATTER_EXAMPLE_DIR "${MATTER_DIR}/examples")
set(MATTER_TOOL_DIR    "${MATTER_DIR}/tools")

# Matter Options
#----------------------------------------#
if(CONFIG_BLE_MATTER_ADAPTER)
    message(STATUS "Enabling BLE for Matter")
    set(CHIP_ENABLE_CHIPOBLE ON)
else()
    message(STATUS "Disabling BLE for Matter")
    set(CHIP_ENABLE_CHIPOBLE OFF)
endif()

if(CONFIG_MATTER_ENABLE_IPV4)
    message(STATUS "Enabling IPv4 for Matter")
    set(CHIP_ENABLE_IPV4 ON)
else()
    message(STATUS "Disabling IPv4 for Matter")
    set(CHIP_ENABLE_IPV4 OFF)
endif()

#OTA is disabled for bridge_port and energy_management_port example zap
if((MATTER_EXAMPLE STREQUAL "bridge_port") OR (MATTER_EXAMPLE STREQUAL "energy_management_port"))
    message(STATUS "Disabling OTA Requestor for Matter")
    set(CHIP_ENABLE_OTA_REQUESTOR OFF)
else()
    message(STATUS "Enabling OTA Requestor for Matter")
    set(CHIP_ENABLE_OTA_REQUESTOR ON)
endif()

#Matter Shell is only enabled for all_clusters
if(MATTER_EXAMPLE STREQUAL "all_clusters")
    message(STATUS "Enabling Shell for Matter")
    set(CHIP_ENABLE_SHELL ON)
else()
    message(STATUS "Disabling Shell for Matter")
    set(CHIP_ENABLE_SHELL OFF)
endif()

if(CONFIG_MATTER_TC_EN)
    message(STATUS "Enabling T&C for Matter")
    set(CHIP_ENABLE_TC ON)
else()
    message(STATUS "Disabling T&C for Matter")
    set(CHIP_ENABLE_TC OFF)
endif()

string(FIND "${MATTER_EXAMPLE}" "_dm"   _DM_FOUND)
string(FIND "${MATTER_EXAMPLE}" "_port" _PORT_FOUND)
if(NOT (${_DM_FOUND} EQUAL -1))
    message(STATUS "${MATTER_EXAMPLE} is port dm example")
    set(PORT_DM_EXAMPLE ON)
    set(PORT_EXAMPLE    OFF)
elseif(NOT (${_PORT_FOUND} EQUAL -1))
    message(STATUS "${MATTER_EXAMPLE} is port example")
    set(PORT_DM_EXAMPLE OFF)
    set(PORT_EXAMPLE    ON)
else()
    message(STATUS "${MATTER_EXAMPLE} is chip app example")
    set(PORT_DM_EXAMPLE OFF)
    set(PORT_EXAMPLE    OFF)
endif()

# Matter General cmakes
#----------------------------------------#
set(MATTER_INCLUDE        "${MATTER_CMAKE_DIR}/matter.cmake")
set(GENERATE_ARGS_GN      "${MATTER_CMAKE_DIR}/utilities/generate_args_gn.cmake")
set(GENERATE_CLUSTER_FILE "${MATTER_CMAKE_DIR}/utilities/generate_cluster_file.cmake")

# Matter Zap File, Cluster File, and Output directory list
#----------------------------------------#
set(ALL_CLUSTERS_OUTPUT_DIR           "${CHIP_DIR}/examples/all-clusters-app/ameba/${c_SOC_TYPE}_build/chip")
set(ALL_CLUSTERS_FILE                 "${ALL_CLUSTERS_OUTPUT_DIR}/codegen/cluster-file.txt")
set(ALL_CLUSTERS_ZAP                  "${CHIP_DIR}/examples/all-clusters-app/all-clusters-common/all-clusters-app.zap")
set(ALL_CLUSTERS_MATTER               "${CHIP_DIR}/examples/all-clusters-app/all-clusters-common/all-clusters-app.matter")
set(AIR_PURIFIER_OUTPUT_DIR           "${CHIP_DIR}/examples/air-purifier-app/ameba/${c_SOC_TYPE}_build/chip")
set(AIR_PURIFIER_FILE                 "${AIR_PURIFIER_OUTPUT_DIR}/codegen/cluster-file.txt")
set(AIR_PURIFIER_ZAP                  "${CHIP_DIR}/examples/air-purifier-app/air-purifier-common/air-purifier-app.zap")
set(AIR_PURIFIER_MATTER               "${CHIP_DIR}/examples/air-purifier-app/air-purifier-common/air-purifier-app.matter")
set(BRIDGE_PORT_OUTPUT_DIR            "${CHIP_DIR}/examples/bridge-app/ameba/${c_SOC_TYPE}_build/chip")
set(BRIDGE_PORT_FILE                  "${BRIDGE_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(BRIDGE_PORT_ZAP                   "${CHIP_DIR}/examples/bridge-app/bridge-common/bridge-app.zap")
set(BRIDGE_PORT_MATTER                "${CHIP_DIR}/examples/bridge-app/bridge-common/bridge-app.matter")
set(ENERGY_MANAGEMENT_PORT_OUTPUT_DIR "${CHIP_DIR}/examples/energy-management-app/ameba/${c_SOC_TYPE}_build/chip")
set(ENERGY_MANAGEMENT_PORT_FILE       "${ENERGY_MANAGEMENT_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(ENERGY_MANAGEMENT_PORT_ZAP        "${CHIP_DIR}/examples/energy-management-app/energy-management-common/energy-management-app.zap")
set(ENERGY_MANAGEMENT_PORT_MATTER     "${CHIP_DIR}/examples/energy-management-app/energy-management-common/energy-management-app.matter")
set(LIGHTING_OUTPUT_DIR               "${CHIP_DIR}/examples/lighting-app/ameba/${c_SOC_TYPE}_build/chip")
set(LIGHTING_FILE                     "${LIGHTING_OUTPUT_DIR}/codegen/cluster-file.txt")
set(LIGHTING_ZAP                      "${CHIP_DIR}/examples/lighting-app/lighting-common/lighting-app.zap")
set(LIGHTING_MATTER                   "${CHIP_DIR}/examples/lighting-app/lighting-common/lighting-app.matter")
set(THERMOSTAT_PORT_OUTPUT_DIR        "${CHIP_DIR}/examples/thermostat/ameba/${c_SOC_TYPE}_build/chip")
set(THERMOSTAT_PORT_FILE              "${THERMOSTAT_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(THERMOSTAT_PORT_ZAP               "${CHIP_DIR}/examples/thermostat/thermostat-common/thermostat.zap")
set(THERMOSTAT_PORT_MATTER            "${CHIP_DIR}/examples/thermostat/thermostat-common/thermostat.matter")

set(AIRCON_PORT_OUTPUT_DIR            "${MATTER_EXAMPLE_DIR}/aircon/${c_SOC_TYPE}_build/chip")
set(AIRCON_PORT_FILE                  "${AIRCON_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(AIRCON_PORT_ZAP                   "${MATTER_EXAMPLE_DIR}/aircon/aircon-app.zap")
set(AIRCON_PORT_MATTER                "${MATTER_EXAMPLE_DIR}/aircon/aircon-app.matter")
set(BRIDGE_DM_OUTPUT_DIR              "${MATTER_EXAMPLE_DIR}/bridge_dm/${c_SOC_TYPE}_build/chip")
set(BRIDGE_DM_FILE                    "${BRIDGE_DM_OUTPUT_DIR}/codegen/cluster-file.txt")
set(BRIDGE_DM_ZAP                     "${MATTER_EXAMPLE_DIR}/bridge_dm/bridge-app.zap")
set(BRIDGE_DM_MATTER                  "${MATTER_EXAMPLE_DIR}/bridge_dm/bridge-app.matter")
set(DISHWASHER_PORT_OUTPUT_DIR        "${MATTER_EXAMPLE_DIR}/dishwasher/${c_SOC_TYPE}_build/chip")
set(DISHWASHER_PORT_FILE              "${DISHWASHER_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(DISHWASHER_PORT_ZAP               "${MATTER_EXAMPLE_DIR}/dishwasher/dishwasher-app.zap")
set(DISHWASHER_PORT_MATTER            "${MATTER_EXAMPLE_DIR}/dishwasher/dishwasher-app.matter")
set(FAN_PORT_OUTPUT_DIR               "${MATTER_EXAMPLE_DIR}/fan/${c_SOC_TYPE}_build/chip")
set(FAN_PORT_FILE                     "${FAN_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(FAN_PORT_ZAP                      "${MATTER_EXAMPLE_DIR}/fan/fan-app.zap")
set(FAN_PORT_MATTER                   "${MATTER_EXAMPLE_DIR}/fan/fan-app.matter")
set(LAUNDRYWASHER_PORT_OUTPUT_DIR     "${MATTER_EXAMPLE_DIR}/laundrywasher/${c_SOC_TYPE}_build/chip")
set(LAUNDRYWASHER_PORT_FILE           "${LAUNDRYWASHER_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(LAUNDRYWASHER_PORT_ZAP            "${MATTER_EXAMPLE_DIR}/laundrywasher/laundrywasher-app.zap")
set(LAUNDRYWASHER_PORT_MATTER         "${MATTER_EXAMPLE_DIR}/laundrywasher/laundrywasher-app.matter")
set(LIGHTING_DM_OUTPUT_DIR            "${MATTER_EXAMPLE_DIR}/light_dm/${c_SOC_TYPE}_build/chip")
set(LIGHTING_DM_FILE                  "${LIGHTING_DM_OUTPUT_DIR}/codegen/cluster-file.txt")
set(LIGHTING_DM_ZAP                   "${MATTER_EXAMPLE_DIR}/light_dm/lighting-app.zap")
set(LIGHTING_DM_MATTER                "${MATTER_EXAMPLE_DIR}/light_dm/lighting-app.matter")
set(MICROWAVEOVEN_PORT_OUTPUT_DIR     "${MATTER_EXAMPLE_DIR}/microwaveoven/${c_SOC_TYPE}_build/chip")
set(MICROWAVEOVEN_PORT_FILE           "${MICROWAVEOVEN_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(MICROWAVEOVEN_PORT_ZAP            "${MATTER_EXAMPLE_DIR}/microwaveoven/microwaveoven-app.zap")
set(MICROWAVEOVEN_PORT_MATTER         "${MATTER_EXAMPLE_DIR}/microwaveoven/microwaveoven-app.matter")
set(REFRIGERATOR_PORT_OUTPUT_DIR      "${MATTER_EXAMPLE_DIR}/refrigerator/${c_SOC_TYPE}_build/chip")
set(REFRIGERATOR_PORT_FILE            "${REFRIGERATOR_PORT_OUTPUT_DIR}/codegen/cluster-file.txt")
set(REFRIGERATOR_PORT_ZAP             "${MATTER_EXAMPLE_DIR}/refrigerator/refrigerator-app.zap")
set(REFRIGERATOR_PORT_MATTER          "${MATTER_EXAMPLE_DIR}/refrigerator/refrigerator-app.matter")

# Set Matter files and directories based on the example
#----------------------------------------#
if(MATTER_EXAMPLE STREQUAL "all_clusters")
    set(CLUSTER_FILE ${ALL_CLUSTERS_FILE})
    set(ZAP_FILE     ${ALL_CLUSTERS_ZAP})
    set(MATTER_FILE  ${ALL_CLUSTERS_MATTER})
    set(OUTPUT_DIR   ${ALL_CLUSTERS_OUTPUT_DIR})
    file(COPY "${MATTER_EXAMPLE_DIR}/chiptest/all-clusters-app.zap"
         DESTINATION "${CHIP_DIR}/examples/all-clusters-app/all-clusters-common/")
elseif(MATTER_EXAMPLE STREQUAL "air_purifier")
    set(CLUSTER_FILE ${AIR_PURIFIER_FILE})
    set(ZAP_FILE     ${AIR_PURIFIER_ZAP})
    set(MATTER_FILE  ${AIR_PURIFIER_MATTER})
    set(OUTPUT_DIR   ${AIR_PURIFIER_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "aircon_port")
    set(CLUSTER_FILE ${AIRCON_PORT_FILE})
    set(ZAP_FILE     ${AIRCON_PORT_ZAP})
    set(MATTER_FILE  ${AIRCON_PORT_MATTER})
    set(OUTPUT_DIR   ${AIRCON_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "bridge_dm")
    set(CLUSTER_FILE ${BRIDGE_DM_FILE})
    set(ZAP_FILE     ${BRIDGE_DM_ZAP})
    set(MATTER_FILE  ${BRIDGE_DM_MATTER})
    set(OUTPUT_DIR   ${BRIDGE_DM_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "bridge_port")
    set(CLUSTER_FILE ${BRIDGE_PORT_FILE})
    set(ZAP_FILE     ${BRIDGE_PORT_ZAP})
    set(MATTER_FILE  ${BRIDGE_PORT_MATTER})
    set(OUTPUT_DIR   ${BRIDGE_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "dishwasher_port")
    set(CLUSTER_FILE ${DISHWASHER_PORT_FILE})
    set(ZAP_FILE     ${DISHWASHER_PORT_ZAP})
    set(MATTER_FILE  ${DISHWASHER_PORT_MATTER})
    set(OUTPUT_DIR   ${DISHWASHER_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "energy_management_port")
    set(CLUSTER_FILE ${ENERGY_MANAGEMENT_PORT_FILE})
    set(ZAP_FILE     ${ENERGY_MANAGEMENT_PORT_ZAP})
    set(MATTER_FILE  ${ENERGY_MANAGEMENT_PORT_MATTER})
    set(OUTPUT_DIR   ${ENERGY_MANAGEMENT_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "fan_port")
    set(CLUSTER_FILE ${FAN_PORT_FILE})
    set(ZAP_FILE     ${FAN_PORT_ZAP})
    set(MATTER_FILE  ${FAN_PORT_MATTER})
    set(OUTPUT_DIR   ${FAN_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "laundrywasher_port")
    set(CLUSTER_FILE ${LAUNDRYWASHER_PORT_FILE})
    set(ZAP_FILE     ${LAUNDRYWASHER_PORT_ZAP})
    set(MATTER_FILE  ${LAUNDRYWASHER_PORT_MATTER})
    set(OUTPUT_DIR   ${LAUNDRYWASHER_PORT_OUTPUT_DIR})
elseif((MATTER_EXAMPLE STREQUAL "light") OR (MATTER_EXAMPLE STREQUAL "light_port"))
    set(CLUSTER_FILE ${LIGHTING_FILE})
    set(ZAP_FILE     ${LIGHTING_ZAP})
    set(MATTER_FILE  ${LIGHTING_MATTER})
    set(OUTPUT_DIR   ${LIGHTING_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "light_dm")
    set(CLUSTER_FILE ${LIGHTING_DM_FILE})
    set(ZAP_FILE     ${LIGHTING_DM_ZAP})
    set(MATTER_FILE  ${LIGHTING_DM_MATTER})
    set(OUTPUT_DIR   ${LIGHTING_DM_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "microwaveoven_port")
    set(CLUSTER_FILE ${MICROWAVEOVEN_PORT_FILE})
    set(ZAP_FILE     ${MICROWAVEOVEN_PORT_ZAP})
    set(MATTER_FILE  ${MICROWAVEOVEN_PORT_MATTER})
    set(OUTPUT_DIR   ${MICROWAVEOVEN_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "refrigerator_port")
    set(CLUSTER_FILE ${REFRIGERATOR_PORT_FILE})
    set(ZAP_FILE     ${REFRIGERATOR_PORT_ZAP})
    set(MATTER_FILE  ${REFRIGERATOR_PORT_MATTER})
    set(OUTPUT_DIR   ${REFRIGERATOR_PORT_OUTPUT_DIR})
elseif(MATTER_EXAMPLE STREQUAL "thermostat_port")
    set(CLUSTER_FILE ${THERMOSTAT_PORT_FILE})
    set(ZAP_FILE     ${THERMOSTAT_PORT_ZAP})
    set(MATTER_FILE  ${THERMOSTAT_PORT_MATTER})
    set(OUTPUT_DIR   ${THERMOSTAT_PORT_OUTPUT_DIR})
else()
    message(FATAL_ERROR "${MATTER_EXAMPLE} example does not exist")
endif()
set(CODEGEN_DIR "${OUTPUT_DIR}/codegen")
set(ARGS_GN "${OUTPUT_DIR}/args.gn")
