set(MATTER_DIR        "${BASEDIR}/component/application/matter")
set(MATTER_CMAKEDIR   "${MATTER_DIR}/project/cmake")
set(CHIPDIR           "${BASEDIR}/third_party/connectedhomeip")
set(MATTER_EXAMPLEDIR "${MATTER_DIR}/examples")
set(MATTER_TOOLDIR    "${MATTER_DIR}/tools")

option(CHIP_ENABLE_AMEBA_DLOG    "Enable Logging for Matter"       OFF)
option(CHIP_ENABLE_CHIPOBLE      "Enable BLE for Matter"           ON)
option(CHIP_ENABLE_IPV4          "Enable IPv4 for Matter"          OFF)
option(CHIP_ENABLE_OTA_REQUESTOR "Enable OTA Requestor for Matter" ON)
option(CHIP_ENABLE_SHELL         "Enable Shell for Matter"         ON)
if(CONFIG_MATTER_TC_EN)
    option(CHIP_ENABLE_TC        "Enable T&C for Matter"           ON)
else()
    option(CHIP_ENABLE_TC        "Enable T&C for Matter"           OFF)
endif()
