include $(MAKE_INCLUDE_GEN)

.PHONY: all clean

# -------------------------------------------------------------------
# Variable Declaration
# -------------------------------------------------------------------
DEVICE_TYPE := otar
OUTPUT_DIR  := $(CHIPDIR)/examples/ota-requestor-app/ameba/build/chip

# -------------------------------------------------------------------
# Build Declaration and Source
# -------------------------------------------------------------------
include $(MATTER_CORE_SRC)

# -------------------------------------------------------------------
# Build Rules
# -------------------------------------------------------------------
include $(MATTER_CORE_RULES)