name: Build Ameba RTOS Matter Docker Image

on:
  pull_request:
    branches:
      - ameba-rtos/release/*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          docker-images: true
          swap-storage: true

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker common base image
      run: |
        docker buildx build --file tools/docker/Dockerfile --tag ameba-rtos-matter:common --load .

    - name: Build AmebaRTOS Docker image
      run: |
        docker buildx build --file tools/docker/ameba-rtos/Dockerfile --tag ameba-rtos-matter:ameba-rtos --load .

    - name: Check Docker images
      run: docker images

    - name: Run Docker container for amebadplus and execute scripts
      run: |
        chmod +x ./tools/docker/ameba-rtos/amebadplus/run_docker_build_scripts.sh
        ./tools/docker/ameba-rtos/amebadplus/run_docker_build_scripts.sh

    - name: Run Docker container for amebalite and execute scripts
      run: |
        chmod +x ./tools/docker/ameba-rtos/amebalite/run_docker_build_scripts.sh
        ./tools/docker/ameba-rtos/amebalite/run_docker_build_scripts.sh

    - name: Run Docker container for amebasmart and execute scripts
      run: |
        chmod +x ./tools/docker/ameba-rtos/amebasmart/run_docker_build_scripts.sh
        ./tools/docker/ameba-rtos/amebasmart/run_docker_build_scripts.sh

    - name: Clean up Docker
      run: docker system prune -af
