name: Build AmebaZ2Plus Matter Docker Image

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main
      - release/*

concurrency:
    group: ${{ github.ref }}-${{ github.workflow }}-${{ (github.event_name == 'pull_request' && github.event.number) || (github.event_name == 'workflow_dispatch' && github.run_number) || github.sha }}
    cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: false
        android: true
        dotnet: true
        haskell: true
        large-packages: false
        docker-images: true
        swap-storage: true

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker common base image
      run: |
        docker buildx build --file tools/docker/Dockerfile --tag ameba-rtos-matter:common --load .

    - name: Build AmebaZ2Plus Docker image
      run: |
        docker buildx build --file tools/docker/amebaz2plus/Dockerfile --tag ameba-rtos-matter:amebaz2plus --load .

    - name: Check Docker images
      run: docker images

    - name: Run Docker container for AmebaZ2Plus and execute scripts
      run: |
        chmod +x ./tools/docker/amebaz2plus/run_docker_build_scripts.sh
        ./tools/docker/amebaz2plus/run_docker_build_scripts.sh

    - name: Clean up Docker
      run: docker system prune -af
