name: Check PR Template Format

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  check-pr-message:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR body for required sections
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.pull_request.body || "";

            if (!body.includes("This PR addresses:") || !body.includes("Verification:")) {
              core.setFailed(`❌ PR description must include both "This PR addresses:" and "Verification:" sections.`);
            }